-- ==========================================
-- VERNEKS DATABASE MIGRATION: RSI ENABLED
-- Tujuan: Memberikan kemampuan Recursive Self-Improvement pada Diah Anna
-- ==========================================

-- 1. CLEANUP & PREPARATION
-- Hapus tabel lama yang mungkin tidak terpakai atau duplikat (Hati-hati di production)
-- DROP TABLE IF EXISTS memory_capsule_log; 
-- DROP TABLE IF EXISTS user_growth_state;
-- Catatan: Jalankan manual di Supabase SQL Editor jika ingin menghapus tabel lama.

-- 2. ALTER TABLE: user_career_profiles
-- Menambahkan kolom untuk "Long Term Memory" dan "RSI State"
ALTER TABLE user_career_profiles 
ADD COLUMN IF NOT EXISTS diah_anna_core_memory TEXT DEFAULT '', -- Memori inti tentang user (tidak berubah sering)
ADD COLUMN IF NOT EXISTS ai_personality_state JSONB DEFAULT '{"empathy_level": 0.8, "directness": 0.5, "humor": 0.3}', -- State kepribadian AI terhadap user ini
ADD COLUMN IF NOT EXISTS rsi_version INTEGER DEFAULT 1, -- Versi evolusi AI untuk user ini
ADD COLUMN IF NOT EXISTS last_rsi_update TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- 3. CREATE TABLE: ai_learned_patterns
-- Menyimpan pola spesifik yang dipelajari AI dari user (Contoh: "User suka jawaban singkat", "User stres setiap Senin")
CREATE TABLE IF NOT EXISTS ai_learned_patterns (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    pattern_category TEXT NOT NULL, -- 'communication_style', 'pain_point', 'strength', 'trigger'
    pattern_description TEXT NOT NULL,
    confidence_score NUMERIC(3,2) DEFAULT 0.50, -- 0.00 s/d 1.00 seberapa yakin AI dengan pola ini
    occurrence_count INTEGER DEFAULT 1,
    last_observed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index untuk pencarian pola cepat
CREATE INDEX IF NOT EXISTS idx_patterns_user ON ai_learned_patterns(user_id);
CREATE INDEX IF NOT EXISTS idx_patterns_category ON ai_learned_patterns(pattern_category);

-- 4. CREATE TABLE: ai_self_improvement_log
-- Log audit bagaimana AI "berpikir" dan memperbaiki diri setelah interaksi
CREATE TABLE IF NOT EXISTS ai_self_improvement_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    session_id TEXT, -- ID sesi chat terkait
    improvement_type TEXT NOT NULL, -- 'strategy_shift', 'tone_adjustment', 'new_insight', 'correction'
    previous_approach TEXT, -- Apa yang dilakukan AI sebelumnya
    new_approach TEXT, -- Apa yang diputuskan AI untuk dilakukan selanjutnya
    reasoning TEXT, -- Mengapa AI berubah pikiran
    impact_score NUMERIC(3,2) DEFAULT 0.0, -- Prediksi dampak perubahan ini
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index untuk audit trail
CREATE INDEX IF NOT EXISTS idx_rsi_log_user ON ai_self_improvement_log(user_id);
CREATE INDEX IF NOT EXISTS idx_rsi_log_type ON ai_self_improvement_log(improvement_type);

-- 5. CREATE TABLE: user_chat_sessions (Refined)
-- Mengganti/Melengkapi user_chat_history dengan struktur yang lebih rapi untuk konteks RSI
CREATE TABLE IF NOT EXISTS user_chat_sessions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    session_title TEXT, -- Auto-generated by AI
    messages JSONB NOT NULL DEFAULT '[]', -- Array pesan {role, content, timestamp}
    summary TEXT, -- Ringkasan sesi oleh AI
    emotional_tone TEXT, -- Deteksi emosi dominan sesi ini
    action_items JSONB DEFAULT '[]', -- Daftar tugas yang dihasilkan dari sesi
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE,
    is_processed_for_rsi BOOLEAN DEFAULT FALSE -- Flag apakah sesi ini sudah dianalisis untuk RSI
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON user_chat_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_started ON user_chat_sessions(started_at);

-- 6. SECURITY (RLS Policies)
-- Pastikan hanya user yang bersangkutan bisa mengakses datanya

-- Policies for ai_learned_patterns
ALTER TABLE ai_learned_patterns ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own patterns" ON ai_learned_patterns;
CREATE POLICY "Users can view own patterns" ON ai_learned_patterns
    FOR SELECT USING (auth.uid() = user_id);
-- Note: Insert/Update biasanya dilakukan oleh Server Side (Service Role), jadi tidak perlu policy public untuk write jika pakai RPC/Edge Function

-- Policies for ai_self_improvement_log
ALTER TABLE ai_self_improvement_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own rsi logs" ON ai_self_improvement_log;
CREATE POLICY "Users can view own rsi logs" ON ai_self_improvement_log
    FOR SELECT USING (auth.uid() = user_id);

-- Policies for user_chat_sessions
ALTER TABLE user_chat_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own sessions" ON user_chat_sessions;
CREATE POLICY "Users can view own sessions" ON user_chat_sessions
    FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can insert own sessions" ON user_chat_sessions;
CREATE POLICY "Users can insert own sessions" ON user_chat_sessions
    FOR INSERT WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Users can update own sessions" ON user_chat_sessions;
CREATE POLICY "Users can update own sessions" ON user_chat_sessions
    FOR UPDATE USING (auth.uid() = user_id);

-- ==========================================
-- SELESAI MIGRASI
-- Langkah selanjutnya: Update kode backend untuk memanfaatkan tabel ini.
-- ==========================================
